//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosgradoWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pays
    {
        public int id { get; set; }
        public string ci { get; set; }
        public string apellidos { get; set; }
        public string nombres { get; set; }
        public double cuotaUno { get; set; }
        public double cuotaDos { get; set; }
        public double cuotaTres { get; set; }
        public double cuotaCuatro { get; set; }
        public double cuotaCinco { get; set; }
        public double cuotaSeis { get; set; }
        public string idCurso { get; set; }
    }
}
